In [4]:
import pandas as pd
import numpy as np
import os

In [5]:
df1 = pd.read_csv('../../Data_list/v2.0/연령별_인구현황/202310_202312_법정동별 연령별인구현황_월간.csv', encoding='cp949')

In [14]:
df1.head(5)

,법정구역,2023년10월_계_총인구수,2023년10월_계_연령구간인구수,2023년10월_계_0세,2023년10월_계_1세,2023년10월_계_2세,2023년10월_계_3세,2023년10월_계_4세,2023년10월_계_5세,2023년10월_계_6세,...,2023년12월_계_3세,2023년12월_계_4세,2023년12월_계_5세,2023년12월_계_6세,2023년12월_계_7세,2023년12월_계_8세,2023년12월_계_9세,2023년12월_계_10세,2023년12월_계_11세,2023년12월_계_12세
0,부산광역시 (2600000000),"3,298,213","279,088","12,673","14,413","15,132","16,222","17,758","19,938","22,152",...,"15,703","17,620","19,562","21,787","24,689","26,730","26,275","25,885","28,593","27,617"
1,부산광역시 중구 (2611000000),"38,831","1,361",57,73,60,66,61,82,109,...,58,62,82,97,115,124,144,148,150,156
2,부산광역시 서구 (2614000000),"104,268","7,069",308,361,398,413,450,479,553,...,410,439,487,521,643,670,668,641,717,726
3,부산광역시 동구 (2617000000),"88,008","5,375",367,421,379,351,372,367,432,...,351,374,356,420,445,449,432,431,476,448
4,부산광역시 영도구 (2620000000),"106,816","6,366",302,310,333,347,413,475,471,...,321,416,448,466,566,583,576,614,673,676

In [40]:
df_city = df1[['법정구역']]
df_sel = df1[df1.columns[df1.columns.str.contains('연령구간인구수')]]
df1 = pd.concat([df_city, df_sel], axis=1)

In [41]:
df.head(5)

,법정구역,2024년01월_계_연령구간인구수,2024년02월_계_연령구간인구수,2024년03월_계_연령구간인구수
0,부산광역시 (2600000000),"275,129","274,055","272,577"
1,부산광역시 중구 (2611000000),"1,303","1,290","1,282"
2,부산광역시 서구 (2614000000),"6,904","6,844","6,793"
3,부산광역시 동구 (2617000000),"5,288","5,235","5,216"
4,부산광역시 영도구 (2620000000),"6,246","6,203","6,173"

In [42]:
df2 = pd.read_csv('../../Data_list/v2.0/연령별_인구현황/202401_202403_법정동별 연령별인구현황_월간.csv', encoding='cp949')

In [43]:
df_city = df2[['법정구역']]
df_sel = df2[df2.columns[df2.columns.str.contains('연령구간인구수')]]
df2 = pd.concat([df_city, df_sel], axis=1)

In [44]:
df2.head(5)

,법정구역,2024년01월_계_연령구간인구수,2024년02월_계_연령구간인구수,2024년03월_계_연령구간인구수
0,부산광역시 (2600000000),"275,129","274,055","272,577"
1,부산광역시 중구 (2611000000),"1,303","1,290","1,282"
2,부산광역시 서구 (2614000000),"6,904","6,844","6,793"
3,부산광역시 동구 (2617000000),"5,288","5,235","5,216"
4,부산광역시 영도구 (2620000000),"6,246","6,203","6,173"

In [49]:
df12 = pd.merge (df1, df2, on='법정구역', how='left')

In [50]:
df12

,법정구역,2023년10월_계_연령구간인구수,2023년11월_계_연령구간인구수,2023년12월_계_연령구간인구수,2024년01월_계_연령구간인구수,2024년02월_계_연령구간인구수,2024년03월_계_연령구간인구수
0,부산광역시 (2600000000),"279,088","277,669","276,498","275,129","274,055","272,577"
1,부산광역시 중구 (2611000000),"1,361","1,347","1,329","1,303","1,290","1,282"
2,부산광역시 서구 (2614000000),"7,069","7,009","6,970","6,904","6,844","6,793"
3,부산광역시 동구 (2617000000),"5,375","5,357","5,333","5,288","5,235","5,216"
4,부산광역시 영도구 (2620000000),"6,366","6,322","6,292","6,246","6,203","6,173"
5,부산광역시 부산진구 (2623000000),"26,907","26,880","26,668","26,645","26,575","26,457"
6,부산광역시 동래구 (2626000000),"26,569","26,439","26,206","26,017","25,976","25,821"
7,부산광역시 남구 (2629000000),"20,927","20,846","20,773","20,699","20,710","20,610"
8,부산광역시 북구 (2632000000),"22,642","22,490","22,365","22,150","21,968","21,862"
9,부산광역시 해운대구 (2635000000),"34,277","34,122","33,924","33,631","33,521","33,362"
10,부산광역시 사하구 (2638000000),"23,065","22,886","22,724","22,441","22,206","22,058"
11,부산광역시 금정구 (2641000000),"14,783","14,688","14,546","14,358","14,196","14,083"
12,부산광역시 강서구 (2644000000),"23,631","23,556","23,375","23,194","23,036","22,925"
13,부산광역시 연제구 (2647000000),"17,048","16,998","17,591","18,327","18,707","18,674"
14,부산광역시 수영구 (2650000000),"12,641","12,535","12,451","12,341","12,309","12,231"
15,부산광역시 사상구 (2653000000),"13,790","13,691","13,610","13,459","13,372","13,264"
16,부산광역시 기장군 (2671000000),"22,637","22,503","22,341","22,126","21,907","21,766"